spring:
  output:
    ansi:
      # enable colored log output by default
      enabled: detect
  datasource:
    url: jdbc:h2:./database
    driver-class-name: org.h2.Driver
    username: "user"
    password: "password"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

#  logging.level.ru.vladislavsumin.cams=debug
logging:
  file: logs/log.txt
  file.max-history: 10
  level:
    net.bramp.ffmpeg: warn
    ru.vladislavsumin.cams: debug

